#!/usr/bin/env node
/**
 * Dump the database schema (no data) to supabase/schema.sql, built from Postgres's catalog:
 * extensions, tables with columns, defaults and constraints, indexes, functions, triggers,
 * row level security, the storage bucket, the watchdog cron job and which migrations were
 * applied. Every statement is safe to re-run. Needs DATABASE_URL (see README).
 *
 *   npm run schema:backup                  write supabase/schema.sql
 *   npm run schema:backup -- --out <file>  somewhere else
 *
 * Restore with scripts/schema-restore.mjs.
 */
import { writeFileSync } from "node:fs";
import postgres from "postgres";

const out = process.argv.includes("--out") ? process.argv[process.argv.indexOf("--out") + 1] : "supabase/schema.sql";
if (!process.env.DATABASE_URL) {
  console.error("DATABASE_URL isn't set (add it to .env.local; see README).");
  process.exit(1);
}
const sql = postgres(process.env.DATABASE_URL, { max: 1, onnotice: () => {} });
const q = (s) => `"${s.replace(/"/g, '""')}"`;
const lines = [];
const add = (...xs) => lines.push(...xs);

add(
  "-- Wholesale Scout schema, dumped by scripts/schema-backup.mjs. No data.",
  `-- Dumped ${new Date().toISOString()}. Safe to re-run. Restore: npm run schema:restore`,
  "",
);

// Extensions.
const exts = await sql`select extname from pg_extension where extname not in ('plpgsql') order by 1`;
add("-- @section extensions");
for (const e of exts) add(`create extension if not exists ${q(e.extname)};`);
add("");

// Tables: columns (no constraints yet, so order doesn't matter).
const tables = await sql`
  select c.oid, c.relname, c.relrowsecurity from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r' order by c.relname`;
add("-- @section tables");
for (const t of tables) {
  const cols = await sql`
    select a.attname, format_type(a.atttypid, a.atttypmod) type, a.attnotnull, pg_get_expr(d.adbin, d.adrelid) def, a.attidentity
    from pg_attribute a left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
    where a.attrelid = ${t.oid} and a.attnum > 0 and not a.attisdropped order by a.attnum`;
  add(`create table if not exists ${q(t.relname)} (`);
  add(cols.map((c) => `  ${q(c.attname)} ${c.type}${c.attidentity === "a" ? " generated always as identity" : c.attidentity === "d" ? " generated by default as identity" : ""}${c.def != null && !c.attidentity ? ` default ${c.def}` : ""}${c.attnotnull ? " not null" : ""}`).join(",\n"));
  add(");");
  // Columns added after the table was first created elsewhere.
  for (const c of cols) {
    add(`alter table ${q(t.relname)} add column if not exists ${q(c.attname)} ${c.type}${c.def != null && !c.attidentity ? ` default ${c.def}` : ""};`);
  }
  if (t.relrowsecurity) add(`alter table ${q(t.relname)} enable row level security;`);
  add("");
}

// Constraints: primary and unique keys first, then checks, then foreign keys.
const cons = await sql`
  select c.conname, t.relname, c.contype, pg_get_constraintdef(c.oid) def
  from pg_constraint c join pg_class t on t.oid = c.conrelid join pg_namespace n on n.oid = t.relnamespace
  where n.nspname = 'public' and c.contype in ('p', 'u', 'c', 'f')
  order by case c.contype when 'p' then 0 when 'u' then 1 when 'c' then 2 else 3 end, t.relname, c.conname`;
add("-- @section constraints");
for (const c of cons) {
  add(`do $$ begin
  if not exists (select 1 from pg_constraint where conname = '${c.conname.replace(/'/g, "''")}' and conrelid = '${q(c.relname).replace(/'/g, "''")}'::regclass) then
    alter table ${q(c.relname)} add constraint ${q(c.conname)} ${c.def};
  end if;
end $$;`);
}
add("");

// Indexes that aren't a constraint's own.
const idx = await sql`
  select i.relname, pg_get_indexdef(i.oid) def from pg_index x
  join pg_class i on i.oid = x.indexrelid join pg_class t on t.oid = x.indrelid join pg_namespace n on n.oid = t.relnamespace
  where n.nspname = 'public' and not exists (select 1 from pg_constraint c where c.conindid = i.oid)
  order by t.relname, i.relname`;
add("-- @section indexes");
for (const i of idx) add(`${i.def.replace(/^CREATE (UNIQUE )?INDEX /, (m, u) => `CREATE ${u ?? ""}INDEX IF NOT EXISTS `).replace(/ ON public\./, " ON ")};`);
add("");

// Functions (after tables: SQL functions check their bodies against them).
const fns = await sql`
  select p.proname, pg_get_functiondef(p.oid) def from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind = 'f'
    and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
  order by p.proname`;
add("-- @section functions");
for (const f of fns) add(`${f.def.replace(/FUNCTION public\./, "FUNCTION ").trim()};`, "");

// Triggers.
const trg = await sql`
  select t.tgname, c.relname, pg_get_triggerdef(t.oid) def from pg_trigger t join pg_class c on c.oid = t.tgrelid
  join pg_namespace n on n.oid = c.relnamespace where n.nspname = 'public' and not t.tgisinternal order by c.relname, t.tgname`;
add("-- @section triggers");
for (const t of trg) add(`drop trigger if exists ${q(t.tgname)} on ${q(t.relname)};`, `${t.def.replace(/ ON public\./, " ON ").replace(/FUNCTION public\./, "FUNCTION ")};`);
add("");

// Functions only the server may call.
add("-- @section grants");
for (const f of await sql`
  select p.proname, pg_get_function_identity_arguments(p.oid) args from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind = 'f' and not has_function_privilege('anon', p.oid, 'execute')
    and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')`) {
  add(`revoke all on function ${q(f.proname)}(${f.args}) from public, anon, authenticated;`);
}
add("");

// Supabase: the storage bucket and the watchdog's schedule (its URL and secret live in Vault).
add("-- @section supabase");
for (const b of await sql`select id, name, public from storage.buckets order by id`.catch(() => [])) {
  add(`insert into storage.buckets (id, name, public) values ('${b.id}', '${b.name}', ${b.public}) on conflict (id) do nothing;`);
}
for (const j of await sql`select jobname, schedule, command from cron.job order by jobname`.catch(() => [])) {
  add(`select cron.unschedule(jobid) from cron.job where jobname = '${j.jobname}';`);
  add(`select cron.schedule('${j.jobname}', '${j.schedule}', $cmd$${j.command}$cmd$);`);
}
add("");

// Which migrations this schema includes, so npm run migrate doesn't apply them again.
add("-- @section migrations");
const applied = await sql`select name from schema_migrations order by name`.catch(() => []);
for (const m of applied) add(`insert into schema_migrations (name) values ('${m.name}') on conflict do nothing;`);

writeFileSync(out, `${lines.join("\n")}\n`);
console.log(`Wrote ${out}: ${tables.length} tables, ${cons.length} constraints, ${idx.length} indexes, ${fns.length} functions, ${trg.length} triggers, ${applied.length} migrations.`);
await sql.end();
